language: go

go:
  - 1.16.x
  - 1.17.x
  - 1.18.x

env:
  - GO111MODULE=on

before_install:
  - go mod tidy

script:
  - go test ./cache -coverprofile=coverage.txt -covermode=atomic
  - go test ./mmap -coverprofile=coverage.txt -covermode=atomic
  - go test ./flock -coverprofile=coverage.txt -covermode=atomic
  - go test ./ioselector -coverprofile=coverage.txt -covermode=atomic
  - go test ./storage -coverprofile=coverage.txt -covermode=atomic
  - go test ./data/art -coverprofile=coverage.txt -covermode=atomic
  - go test ./data/hash -coverprofile=coverage.txt -covermode=atomic
  - go test ./data/set -coverprofile=coverage.txt -covermode=atomic
  - go test ./data/zset -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
