language: go

go:
  - 1.16.x
  - 1.17.x
  - 1.18.x

env:
  - GO111MODULE=on

before_install:
  - go mod tidy

script:
  -  go test -v ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
